#define BOOST_TEST_MODULE Binlog Unittest
#undef BOOST_TEST_NO_MAIN
#include <boost/test/unit_test.hpp>
#include <boost/version.hpp>

BOOST_AUTO_TEST_CASE(check_boost_version)
{
  BOOST_TEST_MESSAGE("Boost version: " << BOOST_VERSION);
  BOOST_TEST(BOOST_VERSION >= 105900);
}

// Since BOOST_TEST_NO_MAIN is undefined,
// main function will be generated by Boost.Test
